### ISSUE TITLE
pip3 doesn't come with python3 anymore (docker build fails)

### ISSUE THREAD

**Issue by zinahe** [xlrl/docker-radicale#1]
Hi,

Thanks for sharing your hardwork. 

Please add **py3-pip** to the list of installed packages in your Dockerfile. As of Alpine 3.12, pip3 doesn't come along with python3. Once radicale is installed, it can be purged just like curl.

Cheers,

**Comment by XelaRellum** [comment]
Thanks a lot for the hint. I have upgrade to Alpine v3.12.1 and fixed the missing dependency.
